### ISSUE TITLE
Migrate test script from Library.core.__main__ to new Tests folder

### ISSUE THREAD

**Issue by kevinkmcguigan** [NSCC-COGS/Aestheta#11]

**Comment by kevinkmcguigan** [comment]
I think we can survive by just writing some little custom python scripts to test individual functions of the core.py codebase. Putting them in /tests folder would help differentiate these type of scripts from the functions in core.

**Comment by bojiang423** [comment]
I have created the Tests package and test_functions.py, however I encountered problems while using this:
1) The import does not work properly. It works if test_functions.py is in the main library
2) Although getTile() function works in python notebook, it doesn't work in my command line, neither running the test from Library.core.__main__ or from Tests.test_functions.test_load_wms_file(). The error is "zsh: segmentation fault  python"

**Comment by bojiang423** [comment]
I created a sample test script in Tests. Everyone can create their own test scripts follow the same patterns. 
To run the test script

```Python
from Aestheta.Tests import basic_functions
basic_functions.test_load_wms_file()
```
