### ISSUE TITLE
Classifier hard coded for 256x256 tiles 

### ISSUE THREAD

**Issue by kevinkmcguigan** [NSCC-COGS/Aestheta#12]
https://github.com/NSCC-COGS/Aestheta/blob/0fe6e4f6cedaab8b7edb9382ec275fe30f3f056d/Library/core.py#L72

**Comment by kevinkmcguigan** [comment]
We should be able to grab the shape of the incoming image file using the array.shape attribute

**Comment by ynandal99** [comment]
I have added the necessary code in classifyImage() function. :)

**Comment by ynandal99** [comment]
> We should be able to grab the shape of the incoming image file using the array.shape attribute

I have added the necessary code in classifyImage() function. :)
