### ISSUE TITLE
Convert GPS coordinate to WMS tile

### ISSUE THREAD

**Issue by kevinkmcguigan** [NSCC-COGS/Aestheta#14]
https://github.com/NSCC-COGS/Aestheta/blob/1db5026fbc72206ef040df95562ff1a2aaef3282/Library/core.py#L7

the getTile function should have the option to get tiles based on a GPS coordinate instead of the tile indexes. This would be more intuitive. The simple math to facilitate can be seen here: https://wiki.openstreetmap.org/wiki/Slippy_map_tilenames

It would be wise to write this conversion as a separate function and then perhaps call that conversion inside getTile if a certain argument is set (such as latlon = True, or if floating point values are passed to x,y)

**Comment by donuty-party** [comment]
Committed.
