### ISSUE TITLE
determine a source for Landsat data 

### ISSUE THREAD

**Issue by kevinkmcguigan** [NSCC-COGS/Aestheta#16]

**Comment by kevinkmcguigan** [comment]
You should be able to hunt down method in the old course tutorials linked on our read me. There we used a text file of links to Landsat files found on Amazon's AWS. This is a bit clunky however and a smoother system would be better.

**Comment by donuty-party** [comment]
Note regarding the Landsat 8 Open Data on AWS: "this dataset is deprecated in favor of the USGS cloud access mechanism. This bucket will be deleted on July 1, 2021."

That'd be good for the duration of this course, but not so useful for future students. USGS is moving to a "requester pays" AWS bucket, which I understand requires and AWS account and would incur data transfer charges. Quick look reveals that wouldn't actually cost much, but would I put my credit card on the line? 🤔 

The alternative is to use Earth Explorer. If we go that route, this looks like it could be helpful: http://kapadia.github.io/usgs/index.html

**Comment by kevinkmcguigan** [comment]
Yep I saw that. I may merge this into a related issue. That link will definitely be worth looking into thanks!

**Comment by donuty-party** [comment]
Just saw the notification from two days ago where you discussed exactly this. 😅

**Comment by Jeeah** [comment]
Earth Explorer is a good idea, due to the AWS method not being able to work after June 1.

**Comment by bojiang423** [comment]
landsatxplore is also an option to download landsat images
https://pypi.org/project/landsatxplore/

**Comment by kevinkmcguigan** [comment]
This is a big next step for us and needs to be sorted out. I'll make this a discussion topic for Tuesday. Cheers!

**Comment by kevinkmcguigan** [comment]
I'm going to close this issue and move the discussion over to #46 - I think we've discovered a number of sources that we can play around with. Nice work all
