### ISSUE TITLE
Otile WMS source not working

### ISSUE THREAD

**Issue by kevinkmcguigan** [NSCC-COGS/Aestheta#2]
This needs to be tested

https://github.com/NSCC-COGS/Aestheta/blob/2302c489d2d21ff8cef54647db9d75da59046cc9/Library/core.py#L30

**Comment by kevinkmcguigan** [comment]
May not be an issue as we will likely just stick to using google and and mapbox WMS for now

**Comment by ynandal99** [comment]
> May not be an issue as we will likely just stick to using google and and mapbox WMS for now

Indeed was an issue, it threw a ConnectionError exception in requests.get() . I have pushed a new commit - replaced otile with esri. It works smoothly.

**Comment by kevinkmcguigan** [comment]
awesome! Thanks Yogesh - that's a good fix
