### ISSUE TITLE
Develop function to load available files directly from OneDrive

### ISSUE THREAD

**Issue by kevinkmcguigan** [NSCC-COGS/Aestheta#43]
Our Eelgrass data is stored on NSCC's OneDrive (a microsoft Azure server). We should investigate if we can load files directly from OneDrive easily using python. This would remove the requirement to manage the data locally or specifically download the files as we need them. This basic functionality could be useful when accessing large eelgrass mapping support files - for example the large aerial photography geotiffs required for project zostera. 

It seems this can be accomplished through the [OneDrive SDK for Python](https://github.com/onedrive/onedrive-sdk-python) which may be rather [straightforward ](https://stackoverflow.com/questions/38531278/using-python-to-download-an-excel-file-from-onedrive-results-in-corrupt-file) but in our case I suspect accessing our data will require authentication.

**Comment by donuty-party** [comment]
First task is to register our app on Azure, to get a client ID. I can't do this with my NSCC credentials… will see if it's possible with a personal account.

After we get a client ID, we'll definitely need to authenticate, probably with credentials in NSCC's Azure Active Directory. If that's true, we might need help from IT.

**Comment by kevinkmcguigan** [comment]
If this ends up being a dead end or a bit of a nightmare we can perhaps find a work around - such as running the process required for the project just locally (on my machine for example)

**Comment by kevinkmcguigan** [comment]
For now I think we can get by using the slightly hacky code that's in that first zostera experiment python notebook. 

It would however be nice to do this more 'correctly' as having onedrive authentication would allow us to download non-public data as well as push data like our classification outputs back to onedrive. 

Perhaps this is a good reason to explore further into Microsoft/azure's alternative to google colab.
