### ISSUE TITLE
Establish the point of Contact for Dr. Webster representing the group.

### ISSUE THREAD

**Issue by kevinkmcguigan** [NSCC-COGS/Aestheta#44]
We need a member of the team to take ownership of the direct communications with Dr Tim Webster. This person will provide Dr Webster with updates on the status of the project, clarify project goals, and communicate information back to the group.

**Comment by kevinkmcguigan** [comment]
Thanks Ensi for taking this on

**Comment by kkmcgg** [comment]
This has more or less been completed naturally
