### ISSUE TITLE
Implement a simple function to load shapefiles 

### ISSUE THREAD

**Issue by kevinkmcguigan** [NSCC-COGS/Aestheta#52]
We will require shapefiles periodically as training data and to check our classification results. Lets investigate some methods for achieving this. A simple library that may facilitate this is pyshape: https://github.com/GeospatialPython/pyshp

An initial iteration of this function could simply load a given shapefile and display it using matplotlib.  The function could be done as an experiment or included into the core.py functions.

**Comment by donuty-party** [comment]
Check this out, too: https://geopandas.org/index.html. It uses https://github.com/Toblerity/Fiona for file access, which uses GDAL. If we end up using pandas, maybe we should use geopandas.

**Comment by ynandal99** [comment]
Hi, I have added the function and pushed in coreJG branch ! Thanks for the links Jeff!

**Comment by kevinkmcguigan** [comment]
Ah! Sorry I missed this today Yogesh. I'll have a look - sounds great!
