### ISSUE TITLE
Write a mission Statement 

### ISSUE THREAD

**Issue by kevinkmcguigan** [NSCC-COGS/Aestheta#7]

**Comment by arraySurfer81210** [comment]
## Aestheta
Our company's purpose is to integrate leading AI technologies with Geospatial applications to provide a fast, automated analysis of satellite and other aerial imagery.

**Comment by arraySurfer81210** [comment]
## Aestheta
Our company's purpose is to integrate leading AI technologies with Geospatial applications to provide a fast, automated analysis of satellite and other aerial imagery.

**Comment by kevinkmcguigan** [comment]
That is too the point and works for me! We'll discuss on Tuesday
