### ISSUE TITLE
getTiles_3x3() function does not work with lat/lon as input

### ISSUE THREAD

**Issue by kevinkmcguigan** [NSCC-COGS/Aestheta#74]
https://github.com/NSCC-COGS/Aestheta/blob/229dbbfe474a2a7740f5e8bf74b0633c80c5feec/Library/core.py#L180

Running the following test:

`import Aestheta.Library.core as core`
`core.getTiles_3x3([-63.5752,44.6488,2],source='google_sat',show=True)`

Gives the following result:

![image](https://user-images.githubusercontent.com/36888812/110215313-72637880-7e7f-11eb-9636-7fefcd96d976.png)

We can determine the tile for these coordinates using our **_tile_from_cords()_** function:

`print(core.tile_from_coords(63.5752,44.6488,2))`

which returns:

[2, 1, 2]

If we plug these into the getTiles_3x3() we see the correct results:

`core.getTiles_3x3([2,1,2],source='google_sat',show=True)`
![image](https://user-images.githubusercontent.com/36888812/110215417-12b99d00-7e80-11eb-8f70-e84634f5f2ed.png)

**Implement a fix in the code base such that this error is resolved**

**Comment by bojiang423** [comment]
I've updated getTile_3x3. Similar to getTile(), program will check if input x & y are float, if yes, call tile_from_coord() to get tile first. 

`# check if input are coordinates (float)
    if isinstance(x, float) and isinstance(y, float):
        x, y, z = tile_from_coords(x, y, z)`

**Comment by kevinkmcguigan** [comment]
great job @bojiang423 thanks!
