### ISSUE TITLE
Implement Normalizing Difference image function in core.py

### ISSUE THREAD

**Issue by kevinkmcguigan** [NSCC-COGS/Aestheta#78]
**create core.norm_diff() as outlined below:**

the function should accept an RGB numpy array such as the google_sat images we have been displaying so far (we have been using the variable name IMG_RGB). The function will a allow the user to specify two image bands (B1 and B2) such that a standard normalized difference (ND) can be calculated, wherein:

ND = (B1-B2) / (B1 + B2)  

This function will return numerical values ranging from -1.0 to 1.0 and will require a 32 bit floating point array, 

The function should return a single band image array array of the same x and y dimensions of the input image. The result should  optionally be able to be plotted using the [matplotlib](https://matplotlib.org/) function imshow() and the plot should display details of the image (meaning that the ND values may require being stretched or manipulated so that the image displays well given the new numerical range) 

An input image may appear as such:

`IMG_RGB = core.getTile([-63.5752,44.6488,2],source='google_sat')`
![image](https://user-images.githubusercontent.com/36888812/110216721-1270d000-7e87-11eb-9cc2-e93f9c6a77f3.png)

and an output from the new function may appear as such:

`ND = core.norm_diff(IMG_RGB, B1=1, B2=2) `
![image](https://user-images.githubusercontent.com/36888812/110216741-2a485400-7e87-11eb-98a4-90abc5eda501.png)

**Comment by Jeeah** [comment]
I have a question. I know I need to make a function in core.py to do the math on the img bands but I am not sure how to access the bands from the google sat tiles.

**Comment by kevinkmcguigan** [comment]
Hey Jeeah! 

I think you're understanding this right but just to be clear: you will not need to access the tile information directly to get the function working function. The function should be stand alone and accept any image, such as the google sat tiles as an argument:
![image](https://user-images.githubusercontent.com/36888812/111464393-7b660c80-86ff-11eb-8533-0d3cb776010a.png)

So! To _run_ the function you will need _some_ image data as an input. You should be able to call the getTile() function to get some google sat images for example, and feed that into the new function. The getTile() function returns tiles as 3-D numpy arrays (rasters with height, width, and 'depth' - which represents the various bands or image colors).

So, 

`IMG_RGB = core.getTile([-63.5752,44.6488,2],source='google_sat')`

then 

`ND = core.norm_diff(IMG_RGB, B1=1, B2=2)`

**So (I think this is your real question) to get access to the individual bands inside the function we can use the following type of numpy syntax:**
![image](https://user-images.githubusercontent.com/36888812/111466060-8de14580-8701-11eb-8718-408f63711925.png)

In numpy this is called [slicing ](https://www.tutorialspoint.com/numpy/numpy_indexing_and_slicing.htm). Slicing allows us to grab and modify certain parts of the numpy array by their index. So in terms of numpy, think of our images as 3-D cubes of pixels :

![image](https://user-images.githubusercontent.com/36888812/111466652-532bdd00-8702-11eb-8d38-5d28727a90c2.png)
Now, yes unfortunately the order of our slices in our case, thinking about the image, is Y,X,Z. The magical **:** character slices _all_ values of a given index. So if we place that for the Y and X axis of the array, our slice will return **_all_** Y and X values. Then if we set our third index Z as the index of our band number (for example band 1 is the index 0), our slice will return that band as a greyscale image. 

So again, to grab a given band from an image represented as a numpy array, **Arr**,  we use the following syntax:

![image](https://user-images.githubusercontent.com/36888812/111468763-ad2da200-8704-11eb-8a0e-fcd16bdddf27.png)

**Comment by kevinkmcguigan** [comment]
good work @Jeeah this function is working I'm going to close this issue
